### Test admin
POST http://localhost:8080/admin/reset
Content-Type: application/json

### Test CreateUser Method
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "madsandcastle@gmail.com",
    "password": "1298086"
}

### Test api login
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "madsandcastle@gmail.com",
    "password": "1298086"
}

### Test chirps
POST http://localhost:8080/api/chirps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIyOWYyNjMyNy0zYjg4LTQyMDMtYWY3MC1mYjQ5Y2NmMDgyODMiLCJleHAiOjE3NDE5MTQ1MzIsImlhdCI6MTc0MTkxMDkzMn0.m-_4xjFLiCM5BVccXZdKlOUYNe4jS2rHZP8M3p2djyg

{
  "body": "Clearly his taste in women is the same as his taste in lawyers: only the very best... with just a right amount of dirty!"
}

### Test Get chirp by ID
GET http://localhost:8080/api/chirps/769fe7b8-b8ab-4046-938a-48bb35f21d0a
Content-Type: application/json

### Test delete chirp by ID
DELETE http://localhost:8080/api/chirps/769fe7b8-b8ab-4046-938a-48bb35f21d0a
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIyOWYyNjMyNy0zYjg4LTQyMDMtYWY3MC1mYjQ5Y2NmMDgyODMiLCJleHAiOjE3NDE5MTQ1MzIsImlhdCI6MTc0MTkxMDkzMn0.m-_4xjFLiCM5BVccXZdKlOUYNe4jS2rHZP8M3p2djyg

### Create User
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "sillygoose@gmail.com",
    "password": "srgpifd34"
}

###
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "sillygoose@gmail.com",
    "password": "srgpifd34"
}

### Test delete chirp (403)
DELETE http://localhost:8080/api/chirps/2b11c820-42dd-4eaa-8c0c-1c6bca1e1a52
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJmMGZjOGE4MS03YTk5LTRmYmYtODZjYS03YTU3N2QyNjFmODUiLCJleHAiOjE3NDE5MTQ4MzUsImlhdCI6MTc0MTkxMTIzNX0.hGuknM07opmz1TsssVchDCZPOKPAI6fiM8N7CLQ75rk

### Test delete chirp (204)
DELETE http://localhost:8080/api/chirps/2b11c820-42dd-4eaa-8c0c-1c6bca1e1a52
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiIxNDM4Y2JlYi00NTU5LTQzYzgtOGM4Mi03OGZlMzYyNGE1YWUiLCJleHAiOjE3NDE5MTM1NzksImlhdCI6MTc0MTkwOTk3OX0.OB6qrKi47s0uXpTUTPxcaTYVN7zOKEpEV625Wl6OS9k

### Test get chirps
GET http://localhost:8080/api/chirps/2b11c820-42dd-4eaa-8c0c-1c6bca1e1a52
Content-Type: application/json

### Check Polka auth key
POST http://localhost:8080/api/polka/webhooks
Content-Type: application/json
Authorization: ApiKey f271c81ff7084ee5b99a5091b42d486e

{
  "data": {
    "user_id": "7204b1c1-aa2c-4cbe-a637-bf8b7c3925bf"
  },
  "event": "user.upgraded"
}



